sudo: false
dist: trusty
language: c
compiler:
    - gcc
addons:
  apt:
    packages:
      - libxcb-randr0-dev
      - libconfig-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libxcb-ewmh-dev
      - libasound2-dev
before_install:
    - export CPPFLAGS=-DOLD_LIBCONFIG
script: make
